# Get the python3 preinstalled image from Docker Hub
FROM python:3

# Copy the source code to the destination
COPY src /usr/src/

# Specify the working directory
WORKDIR /usr/src/

# Run the program output from the previous step
CMD ["python","__init__.py"]
